apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: inference-api-internal
  namespace: inference
spec:
  # This value is updated automatically by the public Terraform deploy workflow.
  targetGroupARN: __INTERNAL_ALB_TARGET_GROUP_ARN__
  targetType: ip
  serviceRef:
    name: inference-api
    port: 80
