name: Private Cloud Platform

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: private-cloud-foundation
  cancel-in-progress: false

jobs:
  platform:
    name: Platform (k8s)
    uses: ./.github/workflows/private-cloud-remote.yml
    with:
      command: apply
      phases: platform
      do_checkout: true
      do_cleanup: true
    secrets: inherit
